In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data/world happiness data 2015-2022.csv")

df.head()

,Year,Happiness Rank,Country,Happiness Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to make life choices,Generosity,Perceptions of Corruption,Dystopia + Residual
0,2015,1,Switzerland,7.587,1.39651,1.34951,0.94143,0.66557,0.29678,0.41978,2.51738
1,2015,2,Iceland,7.561,1.30232,1.40223,0.94784,0.62877,0.43630,0.14145,2.70201
2,2015,3,Denmark,7.527,1.32548,1.36058,0.87464,0.64938,0.34139,0.48357,2.49204
3,2015,4,Norway,7.522,1.45900,1.33095,0.88521,0.66973,0.34699,0.36503,2.46531
4,2015,5,Canada,7.427,1.32629,1.32261,0.90563,0.63297,0.45811,0.32957,2.45176

##Dataset Overview

In [4]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Info:")
df.info()

Shape: (1231, 11)

Columns:
['Year', 'Happiness Rank', 'Country', 'Happiness Score', 'GDP per Capita', 'Social Support', 'Healthy Life Expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of Corruption', 'Dystopia + Residual']

Data Types:
Year                              int64
Happiness Rank                    int64
Country                          object
Happiness Score                 float64
GDP per Capita                  float64
Social Support                  float64
Healthy Life Expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of Corruption       float64
Dystopia + Residual             float64
dtype: object

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1231 entries, 0 to 1230
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Year                          1231 non-null   int64
 1   Happiness Rank                1231 non-null   int64
 2   Country                       1231 non-null   object
 3   Happiness Score               1230 non-null   float64
 4   GDP per Capita                1230 non-null   float64
 5   Social Support                1230 non-null   float64
 6   Healthy Life Expectancy       1230 non-null   float64
 7   Freedom to make life choices  1230 non-null   float64
 8   Generosity                    1073 non-null   float64
 9   Perceptions of Corruption     1072 non-null   float64
 10  Dystopia + Residual           761 non-null    float64
dtypes: float64(8), int64(2), object(1)
memory usage: 105.9+ KB

##Check and Remove Duplicate Rows

In [7]:
print("Duplicate Rows:", df.duplicated().sum())
df = df.drop_duplicates()

print("New Shape:", df.shape)

Duplicate Rows: 0
New Shape: (1231, 11)

##Remove Extra Spaces

In [8]:
# Remove spaces from column names
df.columns = df.columns.str.strip()

# Remove spaces from text values
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

##Convert Numeric Columns

In [9]:
for col in df.columns:
    try:
        df[col] = pd.to_numeric(df[col])
    except:
        pass

##Handel Missing Values

In [11]:
df.isnull().sum()

numeric_cols = df.select_dtypes(include=np.number).columns

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [12]:
df.isnull().sum()

Year                            0
Happiness Rank                  0
Country                         0
Happiness Score                 0
GDP per Capita                  0
Social Support                  0
Healthy Life Expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of Corruption       0
Dystopia + Residual             0
dtype: int64

In [15]:
df.describe()

,Year,Happiness Rank,Happiness Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to make life choices,Generosity,Perceptions of Corruption,Dystopia + Residual
count,1231.000000,1231.000000,1231.000000,1231.000000,1231.000000,1231.000000,1231.000000,1231.000000,1231.000000,1231.000000
mean,2018.450041,77.476848,5.430076,0.976285,1.033014,0.608158,0.440847,0.193955,0.125244,2.042112
std,2.284034,44.512765,1.114907,0.435071,0.329393,0.241152,0.154353,0.104099,0.104053,0.455409
min,2015.000000,1.000000,2.404000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.187000
25%,2016.000000,39.000000,4.585000,0.668500,0.825847,0.439500,0.344500,0.123160,0.061000,1.893500
50%,2018.000000,77.000000,5.410500,1.013580,1.069168,0.639427,0.458135,0.182950,0.094860,2.051250
75%,2020.000000,116.000000,6.225150,1.295921,1.272940,0.790780,0.559000,0.243810,0.148500,2.179000
max,2022.000000,158.000000,7.842000,2.209000,1.644000,1.141000,0.740000,0.838075,0.587000,3.602140

In [16]:
df.dtypes

Year                              int64
Happiness Rank                    int64
Country                          object
Happiness Score                 float64
GDP per Capita                  float64
Social Support                  float64
Healthy Life Expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of Corruption       float64
Dystopia + Residual             float64
dtype: object

##Save Clean File

In [ ]:
df.to_csv("data/cleaned_readytoworkDataset.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!